name: nightly-tests
on: [push, pull_request]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy Builder
        uses: actions/checkout@v4
        with:
          path: builder
          persist-credentials: false

      - name: Run Tests
        run: |
          docker run --rm -v `pwd`/builder:/builder unifyai/builder:latest python3 -m pytest ivy_builder_tests/
